/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** WithRequired type helpers */
type WithRequired<T, K extends keyof T> = T & { [P in K]-?: T[P] };

export interface paths {
  "/questionnaires": {
    /** @description 与えられた条件を満たす20件以下のアンケートのリストを取得します． */
    get: operations["getQuestionnaires"];
    /** @description 新しいアンケートを作成します． */
    post: operations["postQuestionnaire"];
  };
  "/questionnaires/{questionnaireID}": {
    /** @description アンケートの情報を取得します。 */
    get: operations["getQuestionnaire"];
    /** @description アンケートを削除します． */
    delete: operations["delteQuestionnaire"];
    /** @description アンケートの情報を変更します． */
    patch: operations["editQuestionnaire"];
  };
  "/questionnaires/{questionnaireID}/questions": {
    /** @description アンケートに含まれる質問のリストを取得します。 */
    get: operations["getQuestions"];
    /** @description 新しい質問を作成します． */
    post: operations["PostQuestionByQuestionnaireID"];
  };
  "/questions/{questionID}": {
    /** @description 質問を削除します． */
    delete: operations["deleteQuestion"];
    /** @description 質問を変更します． */
    patch: operations["editQuestion"];
  };
  "/responses": {
    /** @description 新しい回答を作成します． */
    post: operations["postResponse"];
  };
  "/responses/{responseID}": {
    /** @description あるresponseIDを持つ回答に含まれる全ての質問に対する自分の回答を取得します */
    get: operations["getResponses"];
    /** @description 回答を削除します． */
    delete: operations["deleteResponse"];
    /** @description 回答を変更します． */
    patch: operations["editResponse"];
  };
  "/users": {
    /**
     * 未実装
     * @description (botおよび除名されたユーザーを除く、全ての) ユーザーのtraQIDのリストを取得します。
     */
    get: operations["getUsers"];
  };
  "/users/me": {
    /** @description 自分のユーザー情報を取得します */
    get: operations["getUsersMe"];
  };
  "/users/me/responses": {
    /** @description 自分のすべての回答のリストを取得します。 */
    get: operations["getMyResponses"];
  };
  "/users/me/responses/{questionnaireID}": {
    /** @description 特定のquestionnaireIdを持つアンケートに対する自分のすべての回答のリストを取得します。 */
    get: operations["getMyResponsesByID"];
  };
  "/users/me/targeted": {
    /** @description 自分が対象になっている アンケートのリストを取得します。 */
    get: operations["getTargetedQuestionnaire"];
  };
  "/users/{traQID}/targeted": {
    /** @description ユーザが対象になっているアンケートのリストを取得します。 */
    get: operations["getTargettedQuestionnairesBytraQID"];
  };
  "/users/me/administrates": {
    /** @description 自分が管理者になっているアンケートのリストを取得します。 */
    get: operations["getMyQuestionnaire"];
  };
  "/groups": {
    /**
     * 未実装
     * @description (全ての) グループのリストを取得します
     */
    get: operations["getGroups"];
  };
  "/results/{questionnaireID}": {
    /** @description あるquestionnaireIDを持つアンケートの結果をすべて取得します。 */
    get: operations["getResults"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description アンケート検索時に回答済みかの状態での絞り込み
     * @enum {string}
     */
    AnsweredType: "answered" | "unanswered";
    /**
     * @description question、questionnaire用のソートの種類
     * @enum {string}
     */
    SortType: "created_at" | "-created_at" | "title" | "-title" | "modified_at" | "-modified_at";
    /**
     * @description response用のsortの種類
     * @enum {string}
     */
    ResponseSortType: "submitted_at" | "-submitted_at" | "title" | "-title" | "modified_at" | "-modified_at";
    /**
     * @description アンケートの結果を, 運営は見られる ("administrators"), 回答済みの人は見られる ("respondents") 誰でも見られる ("public")
     *
     * @example public
     * @enum {string}
     */
    ResShareType: "administrators" | "respondents" | "public";
    NewQuestionnaire: {
      /** @example 第1回集会らん☆ぷろ募集アンケート */
      title: string;
      /** @example 第1回メンバー集会でのらん☆ぷろで発表したい人を募集します らん☆ぷろで発表したい人あつまれー！ */
      description: string;
      /** Format: date-time */
      res_time_limit: string;
      res_shared_to: components["schemas"]["ResShareType"];
      targets: components["schemas"]["Users"];
      administrators: components["schemas"]["Users"];
    };
    NewQuestionnaireResponse: components["schemas"]["QuestionnaireUser"];
    Questionnaire: {
      /** @example 1 */
      questionnaireID: number;
      /** @example 第1回集会らん☆ぷろ募集アンケート */
      title: string;
      /** @example 第1回メンバー集会でのらん☆ぷろで発表したい人を募集します らん☆ぷろで発表したい人あつまれー！ */
      description: string;
      /** Format: date-time */
      res_time_limit: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      modified_at: string;
      res_shared_to: components["schemas"]["ResShareType"];
    };
    QuestionnaireForList: components["schemas"]["Questionnaire"] & {
      /**
       * @description 自分がターゲットになっているかどうか
       *
       * @example true
       */
      is_targeted: boolean;
    };
    QuestionnairesWithPageMax: {
      /** @description 最大ページ数 */
      page_max: number;
      questionnaires: components["schemas"]["QuestionnaireForList"][];
    };
    QuestionnaireByID: components["schemas"]["QuestionnaireUser"] & {
      respondents: components["schemas"]["Users"];
    };
    QuestionnaireMyTargeted: components["schemas"]["Questionnaire"] & {
      /** Format: date-time */
      responded_at: string;
      /** @description 回答済みあるいは下書きが存在する */
      has_response: boolean;
    };
    QuestionnaireMyAdministrates: components["schemas"]["QuestionnaireUser"] & {
      /**
       * @description 回答必須でない場合、またはすべてのターゲットが回答済みの場合、true を返す。それ以外はfalseを返す。
       *
       * @example true
       */
      all_responded: boolean;
      respondents: components["schemas"]["Users"];
    };
    QuestionnaireUser: components["schemas"]["Questionnaire"] & {
      targets: components["schemas"]["Users"];
      administrators: components["schemas"]["Users"];
    };
    /**
     * @description どのタイプの質問か ("Text", "TextArea", "Number", "MultipleChoice", "Checkbox", "LinearScale")
     *
     * @example Text
     * @enum {string}
     */
    QuestionType: "Text" | "TextArea" | "Number" | "MultipleChoice" | "Checkbox" | "LinearScale";
    QuestionBase: {
      /**
       * @description アンケートの何ページ目の質問か
       *
       * @example 1
       */
      page_num: number;
      /**
       * @description アンケートの質問のうち、何問目か
       *
       * @example 1
       */
      question_num: number;
      question_type: components["schemas"]["QuestionType"];
      /** @example 質問文 */
      body: string;
      /**
       * @description 回答必須かどうか
       *
       * @example true
       */
      is_required: boolean;
      options: string[];
      /** @example そう思わない */
      scale_label_right: string;
      /** @example そう思う */
      scale_label_left: string;
      /** @example 1 */
      scale_min: number;
      /** @example 5 */
      scale_max: number;
      /** @example */
      regex_pattern?: string;
      /** @example */
      min_bound?: string;
      /** @example */
      max_bound?: string;
    };
    NewQuestion: components["schemas"]["QuestionBase"] & {
      /** @example 1 */
      questionnaireID: number;
    };
    Question: components["schemas"]["NewQuestion"] & {
      /** @example 1 */
      questionID: number;
    };
    QuestionDetails: components["schemas"]["QuestionBase"] & {
      /** @example 1 */
      questionID: number;
      /** Format: date-time */
      created_at: string;
    };
    NewResponse: {
      /** @example 1 */
      questionnaireID: number;
      body: components["schemas"]["ResponseBody"][];
      /** Format: date-time */
      submitted_at?: string;
    };
    PostResponse: {
      /** @example 1 */
      questionnaireID: number;
      body: components["schemas"]["ResponseBody"][];
      /** @example true */
      temporarily: boolean;
      /** Format: date-time */
      submitted_at?: string;
    };
    Response: components["schemas"]["NewResponse"] & {
      /** Format: date-time */
      modified_at: string;
    };
    ResponseDetails: components["schemas"]["NewResponse"] & {
      /** @example 1 */
      responseID: number;
    };
    ResponseSummary: {
      /** @example 1 */
      responseID: number;
      /** @example 1 */
      questionnaireID: number;
      /** @example 第1回集会らん☆ぷろ募集アンケート */
      questionnaire_title: string;
      /** @example 2017年度入学学部生 */
      description?: string;
      /** Format: date-time */
      res_time_limit?: string;
      /** Format: date-time */
      submitted_at?: string;
      /** Format: date-time */
      modified_at: string;
    };
    ResponseBody: {
      /** @example 1 */
      questionID: number;
      question_type: components["schemas"]["QuestionType"];
      /** @example リマインダーBOTを作った話 */
      response?: string;
      option_response?: string[];
    };
    ResponseResult: WithRequired<components["schemas"]["Response"] & {
      /** @example lolico */
      traqID: string;
      /** @example 1 */
      responseID: number;
    }, "submitted_at">;
    Users: string[];
    User: {
      /** Format: uuid */
      userId: string;
      /** @example lolico */
      traqID: string;
      /** @example ロリ子 */
      displayName: string;
      /** Format: uuid */
      iconFileId: string;
      /** @example trapyojo */
      twitterId: string;
    };
    Me: {
      /** @example lolico */
      traqID: string;
    };
    Group: {
      /** Format: uuid */
      groupId: string;
      /** @example 17B */
      name: string;
      /** @example 2017年度入学学部生 */
      description: string;
      /** @example lolico */
      adminUser: string;
      members: components["schemas"]["Users"][];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: never;
  parameters: {
    /** @description 回答したもの(answered)か未回答のもの(unanswered)かを選別 */
    answeredInQuery?: components["schemas"]["AnsweredType"];
    /** @description 並び順 (作成日時が新しい "created_at", 作成日時が古い "-created_at", タイトルの昇順 "title", タイトルの降順 "-title", 更新日時が新しい "modified_at", 更新日時が古い "-modified_at" ) */
    sortInQuery?: components["schemas"]["SortType"];
    /** @description 並び順 (作成日時が新しい "submitted_at", 作成日時が古い "-submitted_at", タイトルの昇順 "title", タイトルの降順 "-title", 更新日時が新しい "modified_at", 更新日時が古い "-modified_at" ) */
    responseSortInQuery?: components["schemas"]["ResponseSortType"];
    /** @description タイトルの検索 */
    searchInQuery?: string;
    /** @description 何ページ目か (未定義の場合は1ページ目) */
    pageInQuery?: number;
    /** @description 自分がターゲットになっていないもののみ取得 (true), ターゲットになっているものも含めてすべて取得 (false)。デフォルトはfalse。 */
    nontargetedInQuery?: boolean;
    /** @description アンケートID */
    questionnaireIDInPath: number;
    /** @description 質問ID */
    questionIDInPath: number;
    /** @description 回答ID */
    responseIDInPath: number;
    /** @description traQ ID(ex:mazrean) */
    traQIDInPath: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** @description 与えられた条件を満たす20件以下のアンケートのリストを取得します． */
  getQuestionnaires: {
    parameters: {
      query?: {
        sort?: components["parameters"]["sortInQuery"];
        search?: components["parameters"]["searchInQuery"];
        page?: components["parameters"]["pageInQuery"];
        nontargeted?: components["parameters"]["nontargetedInQuery"];
      };
    };
    responses: {
      /** @description 正常に取得できました。アンケートの配列を返します。 */
      200: {
        content: {
          "application/json": components["schemas"]["QuestionnairesWithPageMax"];
        };
      };
      /** @description 与えられた情報の形式が異なります */
      400: {
        content: never;
      };
      /** @description アンケートを正常に取得できませんでした */
      500: {
        content: never;
      };
      /** @description SQLの実行時間が3sを超えた場合。主に正規表現が原因。 */
      503: {
        content: never;
      };
    };
  };
  /** @description 新しいアンケートを作成します． */
  postQuestionnaire: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewQuestionnaire"];
      };
    };
    responses: {
      /** @description 正常にアンケートを作成できました．作成されたアンケートを返します． */
      201: {
        content: {
          "application/json": components["schemas"]["NewQuestionnaireResponse"];
        };
      };
      /** @description 与えられた情報の形式が異なります */
      400: {
        content: never;
      };
      /** @description アンケートを正常に作成できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description アンケートの情報を取得します。 */
  getQuestionnaire: {
    parameters: {
      path: {
        questionnaireID: components["parameters"]["questionnaireIDInPath"];
      };
    };
    responses: {
      /** @description 正常に取得できました。 */
      200: {
        content: {
          "application/json": components["schemas"]["QuestionnaireByID"];
        };
      };
      /** @description アンケートのIDが無効です */
      400: {
        content: never;
      };
      /** @description アンケートが存在しません */
      404: {
        content: never;
      };
      /** @description アンケートを正常に取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description アンケートを削除します． */
  delteQuestionnaire: {
    parameters: {
      path: {
        questionnaireID: components["parameters"]["questionnaireIDInPath"];
      };
    };
    responses: {
      /** @description 正常にアンケートを削除できました． */
      200: {
        content: never;
      };
      /** @description アンケートのIDが無効です */
      400: {
        content: never;
      };
      /** @description アンケートの削除ができませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description アンケートの情報を変更します． */
  editQuestionnaire: {
    parameters: {
      path: {
        questionnaireID: components["parameters"]["questionnaireIDInPath"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewQuestionnaire"];
      };
    };
    responses: {
      /** @description 正常にアンケートを変更できました． */
      200: {
        content: never;
      };
      /** @description アンケートのIDが無効です */
      400: {
        content: never;
      };
      /** @description 正常にアンケートを変更できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description アンケートに含まれる質問のリストを取得します。 */
  getQuestions: {
    parameters: {
      path: {
        questionnaireID: components["parameters"]["questionnaireIDInPath"];
      };
    };
    responses: {
      /** @description 正常に取得できました。 */
      200: {
        content: {
          "application/json": components["schemas"]["QuestionDetails"][];
        };
      };
      /** @description アンケートのIDが無効です */
      400: {
        content: never;
      };
      /** @description 質問のリストを取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description 新しい質問を作成します． */
  PostQuestionByQuestionnaireID: {
    parameters: {
      path: {
        questionnaireID: components["parameters"]["questionnaireIDInPath"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewQuestion"];
      };
    };
    responses: {
      /** @description 正常に質問を作成できました．作成された質問を返します． */
      201: {
        content: {
          "application/json": components["schemas"]["Question"];
        };
      };
      /** @description 正常に作成できませんでした。リクエストが不正です。 */
      400: {
        content: never;
      };
      /** @description 正常に作成できません。主に正規表現が原因。 */
      500: {
        content: never;
      };
    };
  };
  /** @description 質問を削除します． */
  deleteQuestion: {
    parameters: {
      path: {
        questionID: components["parameters"]["questionIDInPath"];
      };
    };
    responses: {
      /** @description 正常に質問を削除できました。 */
      200: {
        content: never;
      };
      /** @description 正常に削除できませんでした。存在しない質問です。 */
      500: {
        content: never;
      };
    };
  };
  /** @description 質問を変更します． */
  editQuestion: {
    parameters: {
      path: {
        questionID: components["parameters"]["questionIDInPath"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewQuestion"];
      };
    };
    responses: {
      /** @description 正常に質問を変更できました． */
      200: {
        content: never;
      };
      /** @description 正常に変更できませんでした。リクエストが不正です。 */
      400: {
        content: never;
      };
      /** @description 正常に変更できませんでした。主に正規表現が原因。 */
      500: {
        content: never;
      };
    };
  };
  /** @description 新しい回答を作成します． */
  postResponse: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PostResponse"];
      };
    };
    responses: {
      /** @description 正常に回答を作成できました．作成された回答を返します． */
      201: {
        content: {
          "application/json": components["schemas"]["ResponseDetails"];
        };
      };
      /** @description 与えられた情報の形式が異なります */
      400: {
        content: never;
      };
      /** @description アンケートの回答の期限がきれたため回答が存在しません */
      404: {
        content: never;
      };
      /** @description 回答期限が過ぎたため回答できません */
      405: {
        content: never;
      };
      /** @description 正常に回答が作成できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description あるresponseIDを持つ回答に含まれる全ての質問に対する自分の回答を取得します */
  getResponses: {
    parameters: {
      path: {
        responseID: components["parameters"]["responseIDInPath"];
      };
    };
    responses: {
      /** @description 正常に取得できました。 */
      200: {
        content: {
          "application/json": components["schemas"]["Response"];
        };
      };
      /** @description responseIDが数値に変換できませんでした */
      400: {
        content: never;
      };
      /** @description アンケートの回答の期限がきれたため回答が存在しません */
      404: {
        content: never;
      };
      /** @description responseIDを取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description 回答を削除します． */
  deleteResponse: {
    parameters: {
      path: {
        responseID: components["parameters"]["responseIDInPath"];
      };
    };
    responses: {
      /** @description 正常に回答を削除できました． */
      200: {
        content: never;
      };
      /** @description 与えられた回答の情報が異なります */
      400: {
        content: never;
      };
      /** @description アンケートの回答の期限がきれたため回答が存在しません */
      404: {
        content: never;
      };
      /** @description 回答期限が過ぎたため回答できません */
      405: {
        content: never;
      };
      /** @description responseIDを取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description 回答を変更します． */
  editResponse: {
    parameters: {
      path: {
        responseID: components["parameters"]["responseIDInPath"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewResponse"];
      };
    };
    responses: {
      /** @description 正常に回答を変更できました． */
      200: {
        content: never;
      };
      /** @description 与えられた回答の情報が異なります */
      400: {
        content: never;
      };
      /** @description アンケートの回答の期限がきれたため回答が存在しません */
      404: {
        content: never;
      };
      /** @description 回答期限が過ぎたため回答できません */
      405: {
        content: never;
      };
      /** @description responseIDを取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /**
   * 未実装
   * @description (botおよび除名されたユーザーを除く、全ての) ユーザーのtraQIDのリストを取得します。
   */
  getUsers: {
    responses: {
      /** @description 正常に取得できました．ユーザーの配列を返します． */
      200: {
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
    };
  };
  /** @description 自分のユーザー情報を取得します */
  getUsersMe: {
    responses: {
      /** @description 正常に取得できました。 */
      200: {
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      /** @description Userが取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description 自分のすべての回答のリストを取得します。 */
  getMyResponses: {
    responses: {
      /** @description 正常に取得できました。回答の配列を返します。 */
      200: {
        content: {
          "application/json": components["schemas"]["ResponseSummary"][];
        };
      };
      /** @description Userが取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description 特定のquestionnaireIdを持つアンケートに対する自分のすべての回答のリストを取得します。 */
  getMyResponsesByID: {
    parameters: {
      path: {
        questionnaireID: components["parameters"]["questionnaireIDInPath"];
      };
    };
    responses: {
      /** @description 正常に取得できました。回答の配列を返します。 */
      200: {
        content: {
          "application/json": components["schemas"]["ResponseSummary"][];
        };
      };
      /** @description questionnaireIDの型が数値ではありません */
      400: {
        content: never;
      };
      /** @description 回答のリストを取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description 自分が対象になっている アンケートのリストを取得します。 */
  getTargetedQuestionnaire: {
    parameters: {
      query?: {
        sort?: components["parameters"]["sortInQuery"];
      };
    };
    responses: {
      /** @description 正常に取得できました。アンケートの配列を返します。 */
      200: {
        content: {
          "application/json": components["schemas"]["QuestionnaireMyTargeted"][];
        };
      };
      /** @description 自分のUserIDが取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description ユーザが対象になっているアンケートのリストを取得します。 */
  getTargettedQuestionnairesBytraQID: {
    parameters: {
      query?: {
        sort?: components["parameters"]["sortInQuery"];
        answered?: components["parameters"]["answeredInQuery"];
      };
      path: {
        traQID: components["parameters"]["traQIDInPath"];
      };
    };
    responses: {
      /** @description 正常に取得できました。アンケートの配列を返します。 */
      200: {
        content: {
          "application/json": components["schemas"]["QuestionnaireMyTargeted"][];
        };
      };
      /** @description 与えらえた情報の形式が異なります */
      400: {
        content: never;
      };
      /** @description 対象となっているアンケートのリストを取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /** @description 自分が管理者になっているアンケートのリストを取得します。 */
  getMyQuestionnaire: {
    responses: {
      /** @description 正常に取得できました。アンケートの配列を返します。 */
      200: {
        content: {
          "application/json": components["schemas"]["QuestionnaireMyAdministrates"][];
        };
      };
      /** @description 自分が管理者となっているアンケートのリストを取得できませんでした */
      500: {
        content: never;
      };
    };
  };
  /**
   * 未実装
   * @description (全ての) グループのリストを取得します
   */
  getGroups: {
    responses: {
      /** @description 正常に取得できました．グループの配列を返します． */
      200: {
        content: {
          "application/json": components["schemas"]["Group"][];
        };
      };
    };
  };
  /** @description あるquestionnaireIDを持つアンケートの結果をすべて取得します。 */
  getResults: {
    parameters: {
      query?: {
        sort?: components["parameters"]["responseSortInQuery"];
      };
      path: {
        questionnaireID: components["parameters"]["questionnaireIDInPath"];
      };
    };
    responses: {
      /** @description 正常に取得できました。アンケートの各質問に対する結果の配列を返します。 */
      200: {
        content: {
          "application/json": components["schemas"]["ResponseResult"][];
        };
      };
      /** @description questionnaireIDの型を数値に変換できませんでした */
      400: {
        content: never;
      };
      /** @description 結果を閲覧する権限がありません。 */
      403: {
        content: never;
      };
      /** @description アンケートの回答の詳細情報一覧が取得できませんでした */
      500: {
        content: never;
      };
    };
  };
}
